### ISSUE TITLE
DebugOutLogger simple logger does not function

### ISSUE THREAD

**Issue by jpikerun** [net-commons/common-logging#104]
The DebugOutLogger uses System.Diagnostics.Debug.WriteLine() to output text, but the nuget is built with release binaries (so the Debug.WriteLine() is disabled).  A debug binary is necessary in order for this simple logger to function as intended.

**Comment by taspeotis** [comment]
Yes, it's most bizarre that this class is shipped in its current state. ReSharper decompiles the code to:

```
protected override void WriteInternal(Common.Logging.LogLevel level, object message, Exception e)
{
  this.FormatOutput(new StringBuilder(), level, message, e);
}
```

The method description is also wrong (it doesn't write to `Console.Out` [like it claims](https://github.com/net-commons/common-logging/blob/master/src/Common.Logging.Portable/Logging/Simple/DebugLogger.cs#L53).)

**Comment by sbohlen** [comment]
This is an interesting (and totally valid) point.  I suspect the comment re: writing to Console.Out is left over from what must have been a copy-paste of the ConsoleOutLogger source (tho TBH, I really don't recall that far back in time!)

Given the fact that System.Diagnostics.Debug is only available in DEBUG binaries, I suppose that the only viable solution would be to ship the DebugOutLogger in its DEBUG rather than RELEASE build.  I'll look into the feasibility of tweaking our build/packaging scripts to handle this properly.

**Comment by taspeotis** [comment]
According to http://stackoverflow.com/a/9987984/242520 you might get away with `#define DEBUG` in just the source file that calls `Debug.WriteLine`.

**Comment by sbohlen** [comment]
Interesting; thanks for that idea, I'll def. experiment a bit to see if that works or not.  TBH I'm not 100% certain how _else_ to potentially solve this.

At least currently, the `DebugOutLogger` is defined in the `Common.Logging.Portable` assembly.  Since this is a 'foundational' assembly that's referenced by (nearly) every other assembly in Common.Logging, compiling it only as DEBUG would almost certainly result in a significant performance degradation in just about all logging (which is contrary to the objective of trying to ensure that logging adds as little overhead as possible to calling code).

Because of this problem, absent your suggestion to use a `#define` we'd conceptually have to build and release two otherwise identically-versioned copies of this assembly, one DEBUG and another RELEASE.  This is generally unappealing as s solution both because of the potential confusion it might create, but also because its somewhat hard for me to imagine a developer actively swapping the DEBUG build of this assembly in and out of their references depending on what type of build they were doing on their calling/consuming project at the time.

Hopefully my experimentation with an inline `#define` will be successful -- I'll test that tomorrow when I'm back at my desk again and advise my results.  Otherwise, the only other poss. solution that immediately comes to mind might be to move the `DebugOutLogger` type to its own assembly (something like `Common.Logging.Debug`) in order to make it explicit just what's intended of it.

Cheers!

**Comment by sbohlen** [comment]
Good news -- the 'local' `#define DEBUG` worked just as advertised, so fixed in https://github.com/net-commons/common-logging/commit/f02e6a606306868ff0240102a134836a8752476d.

**Comment by granadacoder** [comment]
What happened to the ConsoleOutLoggerFactoryAdapter ?  I tried to use DebugLoggerFactoryAdapter / DebugOutLogger and hit this issue.

Using:
nuget\packages\common.logging\3.4.1\lib\netstandard1.3\Common.Logging.dll


{
  "LogConfiguration": {
    "factoryAdapter": {
      "type": "Common.Logging.Simple.DebugLoggerFactoryAdapter, Common.Logging",
      "arguments": {
        "level": "ALL",
        "showDataTime": "true",
        "showLogName": "true",
        "dateTimeFormat": "yyyy/MM/dd HH:mm:ss:fff"
      }
    }
  }
}
