### ISSUE TITLE
Libs in git instead of nuget

### ISSUE THREAD

**Issue by 304NotModified** [net-commons/common-logging#111]
Quick question, 

Why are all the libraries (NLog, log4net etc) in the lib folder,  and not pulled out of nuget? 

Is this a historical problem or am I missing the benefits of the current approach?

**Comment by 304NotModified** [comment]
@sbohlen? 

Should we worry that this library doesn't get the attention that it needs? (issues, questions and pull requests without reply)

**Comment by sbohlen** [comment]
I appreciate your concern, but TBH I'd not worry too much about the care this project gets.  Unfortunately thus far in 2016 I've been repeatedly reminded of the old adage that "_life is what happens while you're busy making other plans_" :-/

The effect of this has been that for the past several months I've had a series of family issues arise that have kept me from applying much time towards this project.  Happily I'm able to report that this is now behind me and I can return to focus energy on Common.Logging again now and for the foreseeable future.

Specifically to your question re: binaries in NuGet vs. in the repo, there are (generally) three core reasons that we don't rely upon NuGet for this project's dependencies: one is historic, one is technical, and one is philosophical:

The historical reason is that the structure, build scripts, dependency management, etc. of Common.Logging pre-dated the arrival of NuGet by several years.  By the time NuGet arrived, we'd been committed to storing the dependent binaries in the repo b/c there previously wasn't any other way to do it :) Changing then (now) would probably add little value given that the alternate approach is already in place for this project.

The technical reason is that in my experience NuGet has (generally) proven itself too unreliable a distribution mechanism upon which to base your project's build.  I can point to several projects to which I contribute with daily CI builds where the dependency upon NuGet for package-restore results in about a 5-10% failure rate on the daily builds (for no other reason than "nuget unable to retrieve package" during package restore due to e.g., timeouts at the NuGet servers).  Having your CI process fail for reasons other than "I broke the build by my own actions" robs CI of its most significant value-prop: being able to provide at-a-glance confirmation of the health of your code base.  Worse, while NuGet (generally) frowns upon package authors removing their packages, there's actually _no guarantee_ that once a package is in NuGet it will remain there for eternity, meaning that NuGet packages are really much more transient than permanent fixtures.

The philosophical reason probably shows my age :) but I come from an era where one of (if not _the_) main point(s) of having a source control system in the first place is to enable the "clean-checkout-and-build" scenario.  If I want to return to what the code looked like 5 years ago, one of the most significant value-props for a source control system is that I should be able to do a clean checkout of the 5-year-old code and have it build for me.  If the binary dependencies aren't in the repo, this can't be guaranteed to actually work.  NuGet represents an unstable, unpredictable external dependency that introduces significant risk to one of the core functions of a source control system.

FWIW, yes, I realize that this line of reasoning taken to its extreme would require me to check into source control the entirety of the .NET framework, the csc.exe compiler, and maybe even a copy of Visual Studio or even Windows in order to ensure that _all_ dependencies are covered.  However, IMO the right "cut-off" point for this line of reasoning is at the point of the dependent libraries -- after that the sheer size of the other dependencies realistically precludes storing them in a source control system :)

If you get from this that I'm not a fan of NuGet, that's not true at all -- I love the centralized package gallery and the (overall) positive influence its had on the .NET OSS ecosystem in general.  However, I'm not at all a fan of NuGet Package Restore (for all the reasons noted above).  IMO NuGet Package Restore optimizes for two resources that are very cheap (disk space and bandwidth) at the expense of a resource that is considerably more expensive (predicable, reliable stability of my build).

Hope this helps clarify the thinking around this, and thanks for the question!

**Comment by 304NotModified** [comment]
Thanks for the comprehensive answer! 

I think nuget would make its easier for outsiders to contribute which can be an important thing in OSS. 

We have seen also failed builds with nuget, bit I think this is last year 1/500 times. Non parallel restore helps in getting things stable. Also you could include the packages folder in git? 

With the upcoming project.json you can upgrade a project dependency by changing one string in the config. :) no need to start visual studio (when using a build server)

**Comment by 304NotModified** [comment]
One side note, I don't see a problem in taking a break with developing, but if people send PRs and don't get any response, then probably they won't do that again in the future.

**Comment by sbohlen** [comment]
Yeah, FWIW I completely agree.  In hindsight if I'd know that this unexpected hiatus was going to last nearly 4 months I'd probably have tried to take steps to ensure that there was someone still covering activity on the project in my absence.  In this case, it was literally death-by-a-thousand-cuts where each week I really thought I was going to be able to return to focus on this again only to discover otherwise.

If this had been a 'planned' break I'd have hopefully been able to take steps to mitigate my absence.  As it was, it just got repeatedly drawn out and as such it never seemed other than that I'd be imminently able to get back to work on this :(   The learning here (for me) is probably to be more eager to "cry uncle" earlier in the future, in the best interests of safeguarding the project's continued health.

**Comment by sbohlen** [comment]
I'm curious as to the thinking behind this statement:

> I think nuget would make its easier for outsiders to contribute which can be an important thing in OSS.

Can you elaborate on how it would reduce friction for contributors if this projects' dependencies were expressed as NuGet packages instead of direct references to binaries stored in the repo --?

I concur that its important to lower the barriers to outsider/newcomer participation in OSS projects and so if I'm overlooking some benefit to using NuGet that could help there I want to ensure that I'm properly considering it.

Thanks!
