### ISSUE TITLE
Stack overflow exception when adding a trace listener.

### ISSUE THREAD

**Issue by B3nCr** [net-commons/common-logging#127]
Hi

I'm trying to get the trace logging from a third party library included in my common.logging output. However, when I add a trace listener I start getting stack overflow exceptions. Presumably something in my chain of listeners and loggers is getting in a loop but I can't really understand what.

The error seems to be thrown from this line but I can't be 100% sure because I don't know how stack trace can be preserved in a stack overflow exception.

        private static readonly Common.Logging.ILog Logger = LogManager.GetLogger<Startup>();

Here's my config. I guess this could be a a question for the log4net team.
    
    <system.diagnostics>
        <sharedListeners>
            <add name="myRealListener"
                 type="Common.Logging.Simple.CommonLoggingTraceListener, Common.Logging"
                 initializeData="DefaultTraceEventType=Information; LoggerNameFormat={0}.{1}; Name=DiagnosticsTraceLogger">
                <filter type="System.Diagnostics.EventTypeFilter" initializeData="Information" />
            </add>
        </sharedListeners>
        <trace>
            <listeners>
                <add name="myRealListener" />
            </listeners>
        </trace>
    </system.diagnostics>
    <common>
        <logging>
            <factoryAdapter type="Common.Logging.Log4Net.Log4NetLoggerFactoryAdapter, Common.Logging.Log4Net1215">
                <arg key="configType" value="INLINE" />
            </factoryAdapter>
        </logging>
    </common>
    
    <log4net debug="true">
        <appender name="RollingLogFileAppender" type="log4net.Appender.RollingFileAppender">
            <file value=".\Log\AppLog" />
            <appendToFile value="true" />
            <rollingStyle value="Date" />
            <datePattern value="yyyy-MM-dd&quot;.log&quot;" />
            <staticLogFileName value="false" />
            <layout type="log4net.Layout.PatternLayout">
                <conversionPattern value="%date [%thread] %-5level %logger [%property{NDC}] - %message%newline" />
            </layout>
        </appender>
        <root>
            <level value="DEBUG" />
            <appender-ref ref="RollingLogFileAppender" />
        </root>
    </log4net>

**Comment by sbohlen** [comment]
I'll take a look at this over the coming weekend and see if I can reproduce it to deduce what might be wrong (assuming its something with Common.Logging and/or your configuration of it or Log4Net).

**Comment by sbohlen** [comment]
I've manged to do some experimenting and I've confirmed that this is definitely a bug in our Log4Net implementation.  The same `CommonLoggingTraceListener` configuration with `Common.Logging` set to use `NLog` instead of `Log4Net` (as in the following config) doesn't evidence the same StackOverlowException and works as intended/advertised.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <sectionGroup name="common">
      <section name="logging" type="Common.Logging.ConfigurationSectionHandler, Common.Logging"/>
    </sectionGroup>
    <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog" />
  </configSections>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
    </startup>
  <system.diagnostics>
    <sharedListeners>
      <add name="myRealListener"
           type="Common.Logging.Simple.CommonLoggingTraceListener, Common.Logging"
           initializeData="DefaultTraceEventType=Information; LoggerNameFormat={0}.{1}; Name=DiagnosticsTraceLogger">
        <filter type="System.Diagnostics.EventTypeFilter" initializeData="Information" />
      </add>
    </sharedListeners>
    <trace>
      <listeners>
        <add name="myRealListener" />
      </listeners>
    </trace>
  </system.diagnostics>
  <common>
    <logging>
      <factoryAdapter type="Common.Logging.NLog.NLogLoggerFactoryAdapter, Common.Logging.NLog40">
        <arg key="configType" value="INLINE" />
      </factoryAdapter>
    </logging>
  </common>


  <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <targets>
      <target name="f1" xsi:type="File" fileName="file1.txt"/>
    </targets>
    <rules>
      <logger name="*" minlevel="Debug" writeTo="f1" />
    </rules>
  </nlog>
  
</configuration>

```

At first glance the origin of the overflow appears to be from within the `CommonLoggingTraceListener` implementation.  But with more exploration I believe I have identified that the actual source of the problem is that the `Log4NetLoggerFactoryAdapter` and the `CommonLoggingTraceListener` are caught in a loop where the `CommonLoggingTraceListener` asks the `Log4NetLoggerFactoryAdapter` to initialize itself which results in a new instance of the `CommonLoggingTraceListener` when it reads the config file which then causes the `Log4NetLoggerFactoryAdapter` to initialize itself (which continues in an endless loop until the system runs out of resources and the StackOverflowException occurs).  When `Common.Logging.Log4Net` is used without the `CommonLoggingTraceListener` there is of course no recursive loop and thus no issue.

I've flagged this as a **BUG** and will definitely need to set some time aside to resolve it before we do the planned 3.4GA release.  In the interim the only other recommendation I can offer would be to switch to another logger (e.g., `NLog`) where this combination doesn't result in the issue or else to await the 3.4GA release that is now planned to contain a fix for this for `Log4Net` (once I'm able to properly figure one out, that is!)

**Comment by B3nCr** [comment]
I've implemented my own trace listener with it's own instance of a Common.Logging ILog logger and call the log methods in there, it seems to work.

**Comment by sbohlen** [comment]
That's interesting -- would you mind sharing your (working) implementation so that I could see what you might be doing differently than the present `CommonLoggingTraceListener`?  It might help me more quickly isolate the source of the underlying problem...

**Comment by B3nCr** [comment]
I've not done anything like that level of implementation, I've just
overridden a write method and pushed the input to a logger.

**Comment by sbohlen** [comment]
Ah, understood -- thanks anyway.  Back to the drawingboard for me on this, I guess :)

**Comment by sbohlen** [comment]
Curious: does your 'replacement' `TraceListener` that you report now works for you also call `LogManager.GetLogger(...)` internally?  Or is it writing elsewhere (independent of `Common.Logging`)?

The reason that I ask is that I'm pretty certain that I've now determined that the underlying cause of the recursion/stack overflow you're reporting:

The `CommonLoggingTraceListener` uses the `Common.Logging.LogManager` to attempt to retrieve an `ILog` instance to use when writing trace output (which is how it was designed to output Trace logging to whatever logger is configured in `Common.Logging`).  For `LogManager` to return a logger, it first has to create the proper `FactoryAdapter` for the configured logger.  The  `FactoryAdapter` for `Log4Net` creates and configures an internal instance of `log4net` to do the actual logging of course.

The problem arises in that `log4net` actually writes to `System.Diagnostics.Trace` as part of its initialization process (e.g., "reading config from file", "configuring logger").  When `log4net` tries to write to Trace as part of its initialization process, its recursively invoking the registered `CommonLoggingTraceListener`.  Because the initial call to the `LogManager` to build the `FactoryAdapter` hasn't yet completed (because we're still in the middle of the first attempt to build the `FactoryAdapter`), the 'next' call to `LogManager.GetLogger(...)` from within `CommonLoggingTraceListener` that's the result of `log4net` writing to Trace as part of its initialization is unable to use the 'already configured' `FactoryAdapter` because technically the first attempt to build the adapter never completed and so there's not (yet) a fully-build `FactoryAdapter` available :(

The call stack looks a bit like this (pseudo-code)....

```
Your app calls Trace.Write("some message")
  --> CommonLoggingTraceListener.Write(...)
    --> LogManager.GetLogger(...)
      --> Log4NetFactoryAdapter.BuildLogger(...)
        --> log4net.Configure(...)
          --> log4net internally calls Trace.Write("log4net is configuring itself via file") [this starts the recursion b/c it re-invokes the registered CommonLoggingTraceListener]
            --> CommonLoggingTraceListener.Write(...)
              --> LogManager.GetLogger(...)
                --> Log4NetFactoryAdapter.BuildLogger(...) 
                  --> [and so on until the overflow occurs] 
```

The reason I was able to get your scenario working under e.g., `NLog` but not `log4net` is that `NLog` doesn't attempt to write to `Trace` as part of its initialization process but `log4net` apparently does.

In my own testing I've found that if I build and register a 'plain' subclass of `System.Diagnostics.TraceListener` (that just overrides the `.Write(...)` and `.WriteLine(...)` methods) I can 100% reproduce your bug as soon as I call `LogManager.GetLogger(...)` from within the overrides.  But so long as I don't interact with `LogManager` in the overrides I can't repro your issue any longer.

This results in a StackOverflow under Log4Net:

```c-sharp
public class NewTraceListener : TraceListener
    {
        public override void Write(string message)
        {
            WriteLine(message);
        }

        public override void WriteLine(string message)
        {
            var logger = LogManager.GetLogger("test");
            logger.Debug(message);
        }
    }
```

...whereas this doesn't:

```c-sharp
public class NewTraceListener : TraceListener
    {
        public override void Write(string message)
        {
            WriteLine(message);
        }

        public override void WriteLine(string message)
        {
            Debug.WriteLine(message);
        }
    }
```

The confirmation (or debunking!) of my theory would be to understand whether your 'replacement' working TraceListener to which you've now switched either does or doesn't call LogManager.GetLogger(...) in its overridden `.Write...` method(s).  If you're somehow still able to call `LogManager.GetLogger(...)` within your alternate TraceListener then this would mean that I need a new theory as to the underlying cause of the issue.  However, if your replacement doesn't call `LogManager.GetLogger(...)` internally then this would tend to confirm/validate my hypothesis as to the root cause of what you're reporting here.

Could you let me know the answer to this question re: your 'replacement' TraceListener implementation --?

**Comment by B3nCr** [comment]
Hi

This is my code...

    public class LoggingTraceListener : TraceListener
    {
        private static readonly ILog Logger = LogManager.GetLogger<LoggingTraceListener>();

        public override void TraceEvent(TraceEventCache eventCache, string source, TraceEventType eventType, int id, string format, params object[] args)
        {
            if (Filter == null || Filter.ShouldTrace(eventCache, source, eventType, id, format, args, null, null))
            {
                // emulates the underlying call to TraceEvent/WriteLine
                string message = string.Format(format, args);
                Logger.Trace(message);
            }
        }
    }

This is my config...

    <system.diagnostics>
        <sources>
            <source name="MembershipReboot"
              switchName="membershipRebootSwitch"
              switchType="System.Diagnostics.SourceSwitch">
                <listeners>
                    <add name="myRealListener" />
                    <remove name="Default" />
                </listeners>
            </source>
        </sources>

        <switches>
            <add name="membershipRebootSwitch" value="All" />
        </switches>
        <sharedListeners>
            <add name="myRealListener"
                 type="Gaist.Authentication.LoggingTraceListener, Gaist.Authentication">
            </add>
        </sharedListeners>
        <trace>
            <listeners>
                <add name="myRealListener" />
            </listeners>
        </trace>
    </system.diagnostics>
    <common>
        <logging>
            <factoryAdapter type="Common.Logging.Log4Net.Log4NetLoggerFactoryAdapter, Common.Logging.Log4Net1215">
                <arg key="configType" value="INLINE" />
            </factoryAdapter>
        </logging>
    </common>
    <log4net debug="true">
        <appender name="RollingLogFileAppender" type="log4net.Appender.RollingFileAppender">
            <file value=".\Log\AppLog" />
            <appendToFile value="true" />
            <rollingStyle value="Date" />
            <datePattern value="yyyy-MM-dd&quot;.log&quot;" />
            <staticLogFileName value="false" />
            <layout type="log4net.Layout.PatternLayout">
                <conversionPattern value="%date [%thread] %-5level %logger [%property{NDC}] - %message%newline" />
            </layout>
        </appender>
        <root>
            <level value="DEBUG" />
            <appender-ref ref="RollingLogFileAppender" />
        </root>
    </log4net>

It doesn't throw a stack overflow exception and breakpoints are hit in the trace event method. I wasn't really trying to debug the tracing when I found the issue, I was trying to debug something else so this code is probably totally wrong, I copied it from the unit tests in this project because I just wanted to see what what being traced by MembershipReboot.

**Comment by sbohlen** [comment]
Thanks for sharing that; its quite helpful to see how you managed to solve this and it does indeed point to confirmation that my hypothesis as to the underlying cause of the issue is correct.

I'll have to experiment a bit with this to be 100% certain, but at first glance I'm pretty certain that what's enabling you to bypass the recursive call/stack overflow condition is that you're storing the logger in a static field:
```c-sharp
private static readonly ILog Logger = LogManager.GetLogger<LoggingTraceListener>();
```
This means that subsequent recursive calls to `Trace.Write(...)` made by Log4net during its own initialization of itself won't actually trigger the endless recursive loop (b/c they won't result in additional calls to `LogManager.GetLogger(...)` but will instead rely upon the single shared instance in the static field). 

I'm near certain that if you were to re-work your listener such that your override of `TraceEvent(...)` were to call `LogManager.GetLogger(...)` in the last line of the method as per this:
```c-sharp
public override void TraceEvent(TraceEventCache eventCache, string source, TraceEventType eventType, int id, string format, params object[] args)
    {
        if (Filter == null || Filter.ShouldTrace(eventCache, source, eventType, id, format, args, null, null))
        {
            // emulates the underlying call to TraceEvent/WriteLine
            string message = string.Format(format, args);
            LogManager.GetLogger<LoggingTraceListener>().Trace(message); //in-line recursive call here
        }
    }
```
...then you'd be right back at the Stack Overflow condition.

As a final assist to us, would you be willing to quickly make such a change and report whether the Stack Overflow condition returns for you?

Thanks again for all the feedback on this; without your continued input I doubt we'd have been able to zero in on the cause nearly as quickly!

**Comment by B3nCr** [comment]
Sorry for the delay, these emails are going into a social filter in gmail
so they're not immediately coming up as new emails.

Yes creating the logger for each event breaks it with a stack overflow
exception.

One thing to note is that my code sinppet was wrong, I excluded the bit
that I thought wasn't relevant. It turns out that the thing i was trying to
to capture wasn't actually using the trace event method, I needed to
overwrite the Write and/or WriteLine methods.

So this code works and doesn't throw StackOverflow...

        public override void Write(string message)
        {
            Logger.Trace(message);
            // ensure we don't get called accidentially
        }

        public override void WriteLine(string message)
        {
            Logger.Trace(message);
            // ensure we don't get called accidentially
        }

This code does throw stack overflow.

        public override void Write(string message)
        {
            LogManager.GetLogger<LoggingTraceListener>().Trace(message);
            // ensure we don't get called accidentially
        }

        public override void WriteLine(string message)
        {
            LogManager.GetLogger<LoggingTraceListener>().Trace(message);
            // ensure we don't get called accidentially
        }

**Comment by sbohlen** [comment]
Fixed in https://github.com/net-commons/common-logging/commit/72a74e82c473b788575c57dfb3ccb948214926fd.

**Comment by B3nCr** [comment]
@sbohlen is this going to be in a pre-release nuget any time soon? I don't fancy building from source to then revert back to nuget in a couple of days time.

Thanks
Ben

**Comment by sbohlen** [comment]
I'll try to push an Alpha2 pre-release package (with this fix) to NuGet later today.  Standby....
