### ISSUE TITLE
"No parent configuration sections allowed" on mono with identical app.config as on windows using .net

### ISSUE THREAD

**Issue by kvloover** [net-commons/common-logging#132]
Hi,

I'm getting the following exception while running on a raspberry pi 3 with mono 4.4:
"parent configuration sections are not allowed"

The weird thing is, it has worked for me before without issues on my raspberry pi running mono 4.4.
It is also working just fine on my windows 10 dev system.

App.config used to be configured inline for nlog, but I've altered it while trying to debug the issue.
(New configuration works fine on windows as well)

Code snippet to test the error (logger is normally a static, but for testing purpose...)

``` c#
            Console.WriteLine($"Logging received : {e.Severity} {e.Source} {e.Message}");
            try
            {
                var logger = Common.Logging.LogManager.GetLogger<Program>();
                Console.WriteLine($"logger found {logger != null}");
                logger?.Info($"{e.Severity} {e.Source} {e.Message}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"{ex.Message}");
            }
```

App.config

``` xml
<configuration>
  <configSections>
    <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 -->
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
    <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 -->
    <sectionGroup name="common">
      <section name="logging" type="Common.Logging.ConfigurationSectionHandler, Common.Logging" />
    </sectionGroup>
  </configSections>

  <common>
    <logging>
      <factoryAdapter type="Common.Logging.NLog.NLogLoggerFactoryAdapter, Common.Logging.NLog41">
        <arg key="configType" value="FILE" />
        <arg key="configFile" value="NLog.config" />
      </factoryAdapter>
    </logging>
  </common>
</configuration>
```

NLog.config

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <targets>
    <!--async="true"-->
    <target name="logfile" xsi:type="File"
            archiveFileName="${basedir}/Archive/DudeBotLog.{#}.txt"
            archiveNumbering="Date"
            archiveEvery="Day"
            archiveDateFormat="yyyyMMdd"
            maxArchiveFiles="7"
            layout="${longdate} ${logger} ${message}"
            fileName="${basedir}/Logfiles/log_${date:format=yyyyMMdd}.log" />
    <target name="console" xsi:type="Console"
            layout="${logger} ${message}" />
  </targets>

  <rules>
    <logger name="*" minlevel="Info" writeTo="logfile" />
    <logger name="*" minlevel="Info" writeTo="console" />
  </rules>
</nlog>
```

**Comment by sbohlen** [comment]
I admit I don't see anything immediately obvious in your provided config file(s) that could account for this.  Unfortunately, I've not got a Raspberry Pi of my own to test this against so I'm at a bit of a loss as to how to assist since it seems you cannot repro outside that environment (?)

Some thoughts:

1. Does the same error repro with other Common.Logging targets/adpaters than just NLog?  Perhaps its an NLog-specific issue of some kind.
1. Pull the Common.Logging source down from GitHub and debug into the source itself -- if you can better identify the origin of the exception, we might be able to further assist.
1. You seem to suggest that this _same_ combination of packages worked find previously(?)  If this is the case, try to focus in on what has changed between when it worked and now (e.g., version of NLog changed?  version of Common.Logging changed?  version of Mono changed?)

Let us know if any of this helps!

**Comment by sbohlen** [comment]
Closed for triage reasons due to lack of feedback/response.  If necessary, please feel free to (re)open this issue as appropriate should the issue persist.
