### ISSUE TITLE
Common.Logging.Core should also support .netstandard libraries

### ISSUE THREAD

**Issue by Portikus** [net-commons/common-logging#145]
Hello everybody,

in my team we are developing some libraries as .netstandard libraries. In this libraries we want to add Common.Logging.Core but the nuget package does not support .netstandard. 
Is it possible that there will be a version that supports .netstandard?

Greetings 

Florian

**Comment by sbohlen** [comment]
Yes, the plans are _definitely_ for `Common.Logging.Core` to support `.NET Standard`.  Evaluating just exactly which version of `.NET Standard` (lowest version) we can get away with is Step 1.  I hope to have this done this coming weekend, after which we can better evaluate the release plans for when this is able to happen (e.g., likely we can fold this into the next 3.x release rather than having to wait for 4.0).

**Comment by donatasvyzasdb** [comment]
Is there an estimate on when release of a stable nuget with  .NET Standard support will be available?

**Comment by sbohlen** [comment]
I can't really provide an estimate until I can determine our level of compat. with the various .NET Standard versions (work scheduled for this coming weekend).  Assuming nothing untoward crops up, I'd expect this could be folded into the next planned 3.x release.

This release is already in a beta and the only real blocker to getting it to a full GA at present is our having time to properly resolve a series of NuGet bundling/PCL profile support issues.  Since these are related/superseded by proper support for .NET Standard, my expectation is that this will (probably) all collapse into a single (easy to resolve) issue, clearing the pending blockers to an RC that can quickly move to GA.

I'll come back to this thread as soon as I have a better handle on timeline, but my blind prediction at present looks something like this:

* 3/20: RC1 posted to NuGet
* 3/31: GA posted to NuGet after an approx. 2-week shake-down cruise for the RC to turn up any lingering issues.

**Comment by sbohlen** [comment]
Closing this issue as superseded by #148.
