### ISSUE TITLE
Log4Net 2.0.7

### ISSUE THREAD

**Issue by jochenjonc** [net-commons/common-logging#150]
Is there a reason why Log4Net 2.0.6 and 2.0.7 are skipped and thus not available?

**Comment by sbohlen** [comment]
No reason other than oversight, I think :)  Thanks for catching that.  My guess is that 2.0.6 and 2.0.7 are binary-compat with 2.0.8 so this is (probably) just a packaging and (re)compilation effort on our part to support it.

I can slate this into the calendar for work towards the end of this week and release a set of 3.4.1 packages that include support for these additional versions in the next several days.

**Comment by sbohlen** [comment]
Fixed in https://github.com/net-commons/common-logging/commit/ab61d2c7a2559df03c968b5061c07e9c56841b22 and pushed to NuGet as `3.4-GA` packages for Log4Net [2.0.6](https://www.nuget.org/packages/Common.Logging.Log4Net206/) and Log4Net [2.0.7](https://www.nuget.org/packages/Common.Logging.Log4Net207/)).
