### ISSUE TITLE
Multiple Factories / Appenders

### ISSUE THREAD

**Issue by ramonsmits** [net-commons/common-logging#8]
I have a situation where I would want to use log4net for colored console output and entlib for persistent logging. I don't see something that allows multiple factories acting like the log4net AppenderCollection. This would be a nice addition and maybe somebody already has made this but I could not find it.

**Comment by sbohlen** [comment]
@ramonsmits 

Just circling back on this to see if anything ever came of it (?)  Since we never received a PR on it, I'm guessing not...do you have any interest in (eventually) pursuing this?

**Comment by ramonsmits** [comment]
I had difficulties in porting my changes to the current master head. I would like to contribute to this project but maybe its interesting in discussing my provious solution first. See if it requires some additional thought.

The primary solution was having a `MultiLog` class that implemented `ILog`. All log methods would iterate through an `IEnumerable<ILog>` firing these methods.

This worked and I started in calling each imlementation in a try..catch so that other loggers would be called even when there are errors but the problem here is that logging rules get *very* complex from then. This is the whole reason why logging frameworks exist.

So then I just removed the try..catch to make the logger responsible for that behavior.

If this implementation would suffice then I'll implement it like this on the current master branch.

**Comment by sbohlen** [comment]
Thanks for letting us know the status.

My immediate thought is that while invoking each logger in the `IEnumerable<ILog>` collection inside its own `try...catch` block would be 'safer', its not clear to me that this would really be necessary per se.

As exists today in each of the various `Common.Logging.XYZ` adapters each individual call to e.g., `logger.LogError(...)` isn't protected (internally) in its own `try...catch` block, so its not clear to me that its a requirement that each individual invocation of the same within your `MultiLog` class would need to be either.

In other words, since the naked `ILog` methods are 'free to throw' unhandled exceptions today, I'm not certain that a collection of them would need to be protected in a `try...catch` block in your proposed scenario. 

That said, I'm also interested in better understanding your comment re: how employing a `try...catch` block around this necessarily leads to significant complexity in your implementation.  I'll admit that I've not actually gone as far as to prototype this myself, but why wouldn't this be as simple as something like the following:

```csharp

public void LogWarn(...)
{
    foreach (var logger in _loggers)  //where '_loggers' is IEnumerable<ILog>
    {
        try
        {
            logger.LogWarn(...); 
        }
        catch ()
        {
            //swallow all exceptions so we safely move on to the next logger
        }
    }
}
```

Its probably the case that I am so over-simplifying this that I'm overlooking some hidden complexity you encountered when you attempted to implement this, but can you help me understand where my thinking is too naive here --?

**Comment by sbohlen** [comment]
@ramonsmits:

FWIW, I took a look @ the work you've done in your own fork (https://github.com/ramonsmits/common-logging) and its more or less what I thought -- and is generally how I would probably have approached it as well.

Rather than my starting from scratch, if possible I'd like to try to incorporate your work into MASTER here as a starting point for this feature.  Do you have any ETA you can offer in re: when you think you might be able to again try to sync your changes into a refresh of the present state of MASTER?

Alternately, if you don't think you're likely to be able to return to this any time soon, could you just issue a PR based on the present state of your FORK so that I can then merge your efforts into MASTER by 'manually' porting them over from your PR?

A quick glance of your changes seems to indicate that there would (likely) be little change to your code itself necessary, although the _location_ of some of that code might need to change (i.e., into other assemblies now that there is `Common.Logging.Core` and `Common.Logging.Portable` to contend with).  My initial guess is that this is (mostly) a refactoring exercise, although of course its also entirely possible it will prove more complicated than that if/when either of us attempt it :)

**Comment by abrasat** [comment]
What is the actual status of this issue, does Common.Logging meanwhile support multiple factory adapters ?

**Comment by sbohlen** [comment]
Sorry for the delay in this; in its current (released) state, multiple adapters are not presently supported.

I actually have a rudimentary version of this working locally, but ran into some challenges in the related changes to the way XML config parsing would need to work to support this.  As mentioned elsewhere, I had some personal issues to address in the first half of 2016 that prevented me from focusing on this, but I'm returning now to focus on this project (and this issue) again.

Hopefully we'll have something in a release shortly -- at a min. I'm hoping to commit this support to MASTER in the next week or so at most.

**Comment by sbohlen** [comment]
OK, I've just merged my initial implementation of this feature and pushed it to MASTER in https://github.com/net-commons/common-logging/commit/b130c7e605310df4e930aed5145d4c087032288c.

I'd really appreciate it if anyone interested in testing it would pull the code, build, and experiment with it to validate not only that it works properly (I've of course already done some rudimentary testing of that) but also to let me know whether the implementation of the feature seems user-friendly from an adoption PoV.

For an example of how to configure this, see [the `App.Config` that drives the initial rough unit test](https://github.com/net-commons/common-logging/blob/master/test/Common.Logging.MultipleLogger.Tests.2010-net40/App.config). 

The salient points are thus:

1.  You need to register the `MultiLoggerFactoryAdapter` as the 'main' adapter for Common.Logging as seen [here](https://github.com/net-commons/common-logging/blob/master/test/Common.Logging.MultipleLogger.Tests.2010-net40/App.config#L13).
2. Each of the 'actual' logger adapters you want to configure needs to be registered under a new `<logging.multipleLoggers>` section as demonstrated [here](https://github.com/net-commons/common-logging/blob/master/test/Common.Logging.MultipleLogger.Tests.2010-net40/App.config#L17-L24).  As you can see, the syntax for the registration of each individual 'actual' logger adapter is the same as you should already be familiar with when registering them as single loggers.
3. In order to properly parse/handle the new `<logging.multipleLoggers>` section, you need to register an additional `ConfigurationSectionHandler` as shown [here](https://github.com/net-commons/common-logging/blob/master/test/Common.Logging.MultipleLogger.Tests.2010-net40/App.config#L7).

Let me know any feedback on this feature (pro or con) and I'll look to address it before I include it in the next release of Common.Logging.

Thanks in advance for any input!

**Comment by abrasat** [comment]
Definitely a very useful feature. For instance this would be a possible usage:

`

            ConsoleOutLoggerFactoryAdapter consoleOutLogger = new ConsoleOutLoggerFactoryAdapter();
            consoleOutLogger.Level = LogLevel.All;
            consoleOutLogger.ShowLevel = true;
            consoleOutLogger.DateTimeFormat = "o";
            consoleOutLogger.ShowDateTime = true;
            consoleOutLogger.ShowLogName = true;

            var log4NetProperties = new Common.Logging.Configuration.NameValueCollection();
            log4NetProperties.Add("configType", "FILE");
            log4NetProperties.Add("configFile", "~/log4net.config");
            var log4NetCommonLoggingFactoryAdapter = new Log4NetLoggerFactoryAdapter(log4NetProperties);

            var loggerFactoryAdapter = new MultiLoggerFactoryAdapter(new List<ILoggerFactoryAdapter> {consoleOutLogger, log4NetCommonLoggingFactoryAdapter });
            Common.Logging.LogManager.Adapter = loggerFactoryAdapter;
`

Could you please upload the actual version containing the MultiLoggerFactoryAdapter as beta release on nuget.org, to make it easier to test ?

**Comment by sbohlen** [comment]
I'd been hoping to delay the next release until after .NET Core went GA, but its now looking as if that's far enough out that delaying until formal/final support of .NET Core can be included is probably impractical.  As such, I'll post a pre-release (probably a beta) of the present state shortly (probably tomorrow) including this new adapter, with an eye towards the next GA release of Common.Logging by the end of the month (May).

**Comment by sbohlen** [comment]
This has now been pushed to NuGet as 3.3.2-Alpha1 (pre-release) to facilitate further testing/evaluation.  Please let us know if any issues turn up in testing/review of this feature.  Assuming no show-stoppers are identified, we'd expect to have this feature formally supported when 3.3.2 goes GA in the next few weeks.

Thanks!

**Comment by abrasat** [comment]
Can you please check the links with the description of the configuration of multipleLoggers, as they seem invalid right now.

**Comment by sbohlen** [comment]
@abrasat thanks for the heads-up; it should be all fixed now.  A subsequent commit actually adjusted the path to the TEST project for the `MultipleLogger`, breaking the prior URLs.  I'm pretty sure I've corrected each of the URLs in the comment now; let me know if you find any that I've missed.

Cheers!

**Comment by sbohlen** [comment]
Closing as RESOLVED.
