### ISSUE TITLE
Dispose LoggerFactoryAdapter

### ISSUE THREAD

**Issue by abrasat** [net-commons/common-logging#89]
Which is the recommended was to dispose the resources of a LoggerFactoryAdapter ? The ILoggerFactoryAdapter does not define any Dispose() or Close() methods.

**Comment by sbohlen** [comment]
Typically `Dispose()`, `Close()`, `IDisposable`, and so on are necessary only when a managed object has unmanaged resources which need to be explicitly released (either for performance reasons or because the garbage collector is unable to properly free unmanaged resources when the it determines the managed object is no longer in scope/use).  This is why you see such approaches used with e.g., database connection wrappers.

Typically, `ILoggerFactoryAdapter` implementations don't fall into this category, and so the garbage collector is (typically) able to properly release their resources when these object go out of scope.  Are you seeing either a memory leak or undue memory pressure from uncollected `ILoggerFactoryAdapter` objects using a memory profiler or other such tools in your use-case?

**Comment by abrasat** [comment]
For instance we have some special logger adapters which log over network (tcp/ip or wcf), and need a "gracious" way to close them (and the established network connections) when the application that uses it is shutting down.

**Comment by sbohlen** [comment]
Ok, that makes sense.

If this is in connection with your own custom ILoggerFactoryAdapter, would it be feasible for your own implementation to simply implement IDisposable as well (and for you to do your cleanup inside the Dispose() method when its called by the finalizer)?

**Comment by abrasat** [comment]
This is probably what I will have to do, but this is not a very elegant solution, as the application can choose between several logger factory adapters which one to use. Some of them will be disposable, and some not (that means that the application will have to check if the logger factory adapter is disposable or not).

**Comment by sbohlen** [comment]
TBH this doesn't seem _that_ inelegant to me (testing whether its safe to call a method before calling it).  Its really just a single line of code (a brief `if` statement) in whatever is responsible for managing the `ILoggerFactoryAdapter` instances in your architecture:
```csharp
//somewhere earlier:
ILoggerFactoryAdapter adapter;

//when ready to release:
if (adapter is IDisposable)
    adapter.Dispose();
```
Unfortunately, as there wasn't an expectation that `ILoggerFactoryAdapter` implementations would take a dependency on unmanaged resources, there's no other viable alternative unless we were to add `IDisposable` to the `ILoggerFactoryAdapter` interface (a breaking change for existing clients).

Hope this helps, and sorry there's no viable alternative we can offer you here.  I'm going close this issue for now; feel free to re-open it should you discover that the recommended approach is insufficient for your needs.

**Comment by sbohlen** [comment]
Sorry, that won't (quite) work; it needs to be...
```csharp
//somewhere earlier:
ILoggerFactoryAdapter adapter;

//when ready to release:
var disposableCandidate = adapter as IDisposable;

if (disposableCandidate != null)
    disposableCandidate.Dispose();
```
That's what I get for using a textbox as my IDE late at night when I should really be asleep already :)

Not _quite_ a one-liner, but still not _that_ inelegant!
