### ISSUE TITLE
Common.Logging.Portable portability ?

### ISSUE THREAD

**Issue by abrasat** [net-commons/common-logging#90]
I let the Microsoft .NET Portability Analyzer Visual Studio add-on (https://visualstudiogallery.msdn.microsoft.com/1177943e-cfb7-4822-a8a6-e56c7905292b) analyze the Common.Logging.Portable 3.1.0 implementation. Could you please take a look regarding the few (especially Windows 8.1) incompatibility issues ?
Thanks in advance.

**Comment by sbohlen** [comment]
Hmm...I wasn't aware of this tool, but am thankful for your pointing it out to me.  I'll take a look at the issues raised in the reports and see if there are viable work-arounds for them that we can implement (hopefully without introducing breaking changes).

TBH, for some of these reflection-specific issues (e.g., `Type.GetMethod(...)`, `Type.GetConstructor(...)`) there may not in fact be Windows 8.1/Windows Phone 8.1 equivalents since the reflection subsystem in WinRT is intentionally limited to reduce the threat/attack surface to which an app might expose itself.

I'll investigate each of these and report back my findings as soon as possible.

**Comment by sbohlen** [comment]
Just looping back with a quick update after an initial investigation...

* There are no issues identified by the utility in the `Common.Logging.Core` PCL
* There are issues found in the `Common.Logging.Portable` PCL that relate primarily to the Reflection APIs and secondarily to a small amount of exception-logging metadata that interacts with the Stack API and the Threading API 

At first glance it appears as if most (all?) of the necessary APIs have an equivalent in WinRT for Win/WinPhone 8.x (https://msdn.microsoft.com/en-us/library/windows/apps/hh535795.aspx) so on the surface its possible to resolve the issues.

However, it also appears as if switching the reflection code to use the WinRT-compatible reflection APIs would require removing support for .NET 4.0 from `Common.Logging.Portable` and having that library target NET 4.5 instead (since the necessary APIs for proper reflection in WinRT aren't available until .NET 4.5, the version of the BCL against which the WinRT profile is defined).

I cannot be certain without further investigation/exdperimentation, but my initial thinking is that this would likely break `Common.Logging.Silverlight`, since this has a dependency on `Common.Logging.Portable` and its targeting SL5.  Once `Common.Logging.Portable` moves to support only .NET 4.5 and higher, I don't believe that SL5-based projects can any longer reference it.

That said, it may be that its more important that `Common.Logging.Portable` support WinRT 8.x (and the upcoming WinRT 10) than that it continue to support Silverlight and 'legacy' WindowsPhone apps, so even if this forces a choice between the two, pretty clearly the right choice is to come down on the side of the future WinRT support rather than the legacy Silverlight support moving forward.

I'll perform some additional investigation/experimentation over the next several days and advise my results.

**Comment by sbohlen** [comment]
Just by way of an update on this, its proving more complex that initially expected but its still something that we very much plan to address.  Its likely that this will result in a new `Common.Logging.dll` that is specific to WinRT support (sim. the way that there is today a sep. `Common.Logging.dll` for e.g., Silverlight support).

Our expectation is to have this addressed/resolved (and released to NuGet) by mid-month (July).

**Comment by sbohlen** [comment]
Fixed in https://github.com/net-commons/common-logging/releases/tag/3.3.0.GA.
